const data = {
  products: [
    {
      name: "shirt",
      slug: "shirt-blue",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-8-580x870(1).jpg",
      price: 80,
      rating: 4.8,
      countInStock: 10,
      description: "A beautiful blue shirt",
    },
    {
      name: "teddy",
      slug: "pink-teddy",
      sexOrAge: "For Girls",
      category: "toys",
      image: "/toys-4-580x870.jpg",
      price: 4,
      rating: 5,
      countInStock: 10,
      description: "soft and fluffy",
    },
    {
      name: "shirt",
      slug: "shirt-pink",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-11-580x870.jpg",
      price: 60,
      rating: 4.6,
      countInStock: 8,
      description: "A popular shirt",
    },
    {
      name: "short",
      slug: "short-white",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-6-580x870.jpg",
      price: 25,
      rating: 4,
      countInStock: 25,
      description: "Popular beach short",
    },
    {
      name: "short",
      slug: "short-green",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-10-580x870.jpg",
      price: 30,
      rating: 4.3,
      countInStock: 18,
      description: "Popular beach short",
    },
    {
      name: "pullover",
      slug: "pullover-with-dinosaurs",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-4-580x870.jpg",
      price: 20,
      rating: 4.6,
      countInStock: 15,
      description: "A popular pullover",
    },
    {
      name: "teddy",
      slug: "monkey-teddy",
      sexOrAge: "For Boys",
      category: "toys",
      image: "/for-home-6-580x870.jpg",
      price: 3,
      rating: 5,
      countInStock: 10,
      description: "adorable and soft",
    },
    {
      name: "pullover",
      slug: "pullover-ocher",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-8-580x870.jpg",
      price: 25,
      rating: 4.8,
      countInStock: 15,
      description: "A beautiful pullover",
    },
    {
      name: "shirt",
      slug: "shirt-white",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-1-580x870.jpg",
      price: 70,
      rating: 4.5,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "cup",
      slug: "pink-cup",
      sexOrAge: "For Girls",
      category: "home",
      image: "/for-home-12-1-580x870.jpg",
      price: 2,
      rating: 5,
      countInStock: 10,
      description: "cup with ears",
    },
    {
      name: "coat",
      slug: "thick-coat",
      sexOrAge: "For Boys",
      category: "clothes",
      image: "/boys-5-580x870.jpg",
      price: 80,
      rating: 4.2,
      countInStock: 22,
      description: "A thick coat for boys",
    },
    {
      name: "teddy",
      slug: "white-teddy",
      sexOrAge: "For Girls",
      category: "toys",
      image: "/toys-5-580x870.jpg",
      price: 4,
      rating: 5,
      countInStock: 10,
      description: "soft and fluffy",
    },
  ],
};

export default data;
