const data = {
  products: [
    {
      name: "Shirt",
      slug: "shirt",
      category: "For Boys",
      image: "/boys-1-580x870.jpg",
      price: 70,
      rating: 4.5,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Shirt",
      slug: "shirt",
      category: "For Boys",
      image: "/boys-8-580x870(1).jpg",
      price: 80,
      rating: 4.8,
      countInStock: 10,
      description: "A beautiful blue shirt",
    },
    {
      name: "Shirt",
      slug: "shirt",
      category: "For Boys",
      image: "/boys-11-580x870.jpg",
      price: 60,
      rating: 4.6,
      countInStock: 8,
      description: "A popular shirt",
    },
    {
      name: "Short",
      slug: "short",
      category: "For Boys",
      image: "/boys-10-580x870.jpg",
      price: 30,
      rating: 4.3,
      countInStock: 18,
      description: "Popular beach short",
    },
    {
      name: "Short",
      slug: "short",
      category: "For Boys",
      image: "/boys-6-580x870.jpg",
      price: 25,
      rating: 4,
      countInStock: 25,
      description: "Popular beach short",
    },
    {
      name: "Pullover",
      slug: "pullover",
      category: "For Boys",
      image: "/boys-4-580x870.jpg",
      price: 20,
      rating: 4.6,
      countInStock: 15,
      description: "A popular pullover",
    },
    {
      name: "Pullover",
      slug: "pullover",
      category: "For Boys",
      image: "/boys-8-580x870.jpg",
      price: 25,
      rating: 4.8,
      countInStock: 15,
      description: "A beautiful pullover",
    },
    {
      name: "Coat",
      slug: "coat",
      category: "For Boys",
      image: "/boys-5-580x870.jpg",
      price: 80,
      rating: 4.2,
      countInStock: 22,
      description: "A thick coat for boys",
    },
  ],
};

export default data;
