import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const BaseLayout = ({ title, children }) => {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>{title ? title + " - ecommerce" : "ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex-grow mb-10">
        <Navbar />
        <main className="flex-grow">{children}</main>
      </div>
      <Footer className="mt-auto" />
    </div>
  );
};

export default BaseLayout;
